### ISSUE TITLE
Need assistance with instructions line 8

### ISSUE THREAD

**Issue by tbloomingdale** [Rappetor/Sovol-SV08-Mainline#100]
I am on instructions line 8 and am stuck. I for some reason can't figure how or where to change . I follow the instructions and I keep getting usb-Katapult_stm32f103xe_ when doing ls /dev/serial/by-id/ . In my printer.cfg it is showing
 [mcu]
serial: /dev/serial/by-id/usb-Klipper_stm32f103xe_34FFD805334D593515530651-if00

restart_method: command     

[mcu extra_mcu]
serial: /dev/serial/by-id/usb-Klipper_stm32f103xe_52FF6F067167485737111787-if00
restart_method: command 

I can't move forward with the instructions as on the Klipper head and board program section , I get error.

Thank you,

Todd.

**Comment by cyaneo** [comment]
I stuck with Flashing Error:

```
my printer.cfg (replaced the S/N for security):
[mcu]
[mcu]      
serial: /dev/serial/by-id/usb-Klipper_stm32f103xe_44EEAA454554555544545555-if00
restart_method: command     

[mcu extra_mcu]
serial: /dev/serial/by-id/usb-Klipper_stm32f103xe_44EEAA454554555544545544-if00
restart_method: command  
```  

The ls -la /dev/serial/by-id/ give me:

usb-katapult_stm32f103xe_44EEAA454554555544545555-if00 -> ../../ttyACM1
usb-katapult_stm32f103xe_44EEAA454554555544545544-if00 -> ../../ttyACM0


When running 

cd "$HOME/klipper" && ./update_klipper_mcus_sv08.sh
In the MCU updater menu choose option 1 'HOST MCU'. In the menuconfig screen for the HOST,choose the following option(s) and add PA1,PA3 on the last line (GPIO pins , if you want MCU fan and light during boot), when ready press Q to quit & save.

I choose 1 HOST MCU.

Cleaning and building Klipper firmware for HOST MCU.

Check on the following screen that the parameters are correct for the
HOST
firmware. Press [Enter] to continue..
After [Enter] I get

Flashing Klipper to HOST MCU.

Flashing Serial Device /dev/serial/by-id/usb-katapult_stm32f103xe_32FFDD054747363009841857-if00, baud 250000
ERROR:root:Flash Error
Traceback (most recent call last):
  File "/home/biqu/katapult/scripts/flashtool.py", line 678, in main
    await sock.run(args.device, args.baud, fpath)
  File "/home/biqu/katapult/scripts/flashtool.py", line 610, in run
    raise FlashError("Invalid firmware path '%s'" % (fw_path))
FlashError: Invalid firmware path '/home/biqu/klipper/host_mcu_klipper.bin'

HOST MCU flashed. Check for errors and press [Enter] to continue..
