### ISSUE TITLE
Can not update MCU 'extra_mcu' config as it is shutdown

### ISSUE THREAD

**Issue by MrD003** [Rappetor/Sovol-SV08-Mainline#106]
Hey there,
I just finished the ReadMe.md and did all the steps as described.

when i try to calibrate z-offset from the lcd menu i am getting this error on the mainsail dashboard:

![image](https://github.com/user-attachments/assets/963bde3d-06e3-4d6b-b492-43b8df5752a1)

can anyone provide their printer.cfg and macro.cfg as well as the lcd files? maybe i importet something wrong there...

[moonraker (2).log](https://github.com/user-attachments/files/17999112/moonraker.2.log)
[klippy (2).log](https://github.com/user-attachments/files/17999113/klippy.2.log)

does anyone know why i am getting this error and how to fix it?

Best Regards

**Comment by chrisf4lc0n** [comment]
This looks like you have not flashed the MCUs properly or serial IDs for MCUs are incorrect.

**Comment by MrD003** [comment]
i think i solved it, as one fan connector was only partly connected.

**Comment by MrD003** [comment]
i think i solved it, as one fan connector was only partly connected.
