### ISSUE TITLE
/home/biqu/printer_data/config/moonraker_obico_macros.cfg missing

### ISSUE THREAD

**Issue by epyon314** [Rappetor/Sovol-SV08-Mainline#116]
I am to the point where I flash the mcu however klipper is coming up with "include file  '/home/biqu/printer_data/config/moonraker_obico_macros.cfg' does not exist"

**Comment by FoldZero** [comment]
yeah  the *obico* was deleted with a vengeance from the SOVOL cfg' as it was a pain in the ass
