### ISSUE TITLE
sovol-menu.cfg calls for SHAPER_CALIBRATE, but that macro is not included anywhere

### ISSUE THREAD

**Issue by butterbutts** [Rappetor/Sovol-SV08-Mainline#118]
Both the belt test and auto-calibrate menu options in the sovol-menu.cfg call for SHAPER_CALIBRATE, but that macro is not anywhere in any of the configs.
As far as I can tell there is no way to run input shaping because of this.

**Comment by jedi1024** [comment]
This is a built-in command from [Klipper](https://www.klipper3d.org/G-Codes.html?h=shaper_calibrate#shaper_calibrate)

**Comment by butterbutts** [comment]
I'm getting an error when I try to run it, it says unknown command.

**Comment by jedi1024** [comment]
You need [resonance_tester] in printer.cfg

https://www.klipper3d.org/G-Codes.html?h=shaper_calibrate#resonance_tester

**Comment by butterbutts** [comment]
Okay, thank you. Somehow it got re-commented out.
