### ISSUE TITLE
Todo: Separate File for default screen or klipperscreen

### ISSUE THREAD

**Issue by mon5termatt** [Rappetor/Sovol-SV08-Mainline#21]
The "menu" file is not needed when an HDMI screen is connected.

Additionally some files need to be changed when running an HDMI screen. 
Currently by default the HDMI screen is upside down on this branch.

**Comment by mon5termatt** [comment]
Additionally when the default screen is disconnected the beeper and screen neopixel config does not need to be in printer.cfg

**Comment by mon5termatt** [comment]
Having a separate file or folder for default or HDMI could keep the printer.cfg more universal by only [include]'ing the specific config file

**Comment by galosre** [comment]
I like to have both the small screen and the HDMI

**Comment by Agash** [comment]
> I like to have both the small screen and the HDMI

Should be easily doable with the suggested way of OP. Generally, a more composable configuration would be beneficial for the stock experience as well as for mods.

**Comment by mon5termatt** [comment]
https://github.com/Rappetor/Sovol-SV08-Mainline/pull/26
