### ISSUE TITLE
Questi on - Could the pinout of the 4 pin STLink connector be added

### ISSUE THREAD

**Issue by WZ9V** [Rappetor/Sovol-SV08-Mainline#34]
Could the Motherboard and Toolhead 4 pin connectors used to do the STLink updates be documented?

The pictures help some but having the labels on the diagram would make things more clear in my opinion.

**Comment by mon5termatt** [comment]
im at work but ill see what i can do when i get back home.

**Comment by WZ9V** [comment]
Thanks that is great.

**Comment by WZ9V** [comment]
> @WZ9V Is this better for you like this? If so we can close the issue. The pins themselves are quite clearly marked on the boards so I'd assume this is enough info to get it done.

I missed that the labels on the tool head are on the board below the board with the pins.

**Comment by WZ9V** [comment]
That is awesome.  Exactly what I was thinking.
