### ISSUE TITLE
SV08 vs BTT Pi v1.2

### ISSUE THREAD

**Issue by cyaneo** [Rappetor/Sovol-SV08-Mainline#44]
Long time ago I upgraded my SV06+ with Klipper (thank's to bassam!) using a PTT Pi v1.2.
This Board use the same BTT CB1 image as in this tutorial.
This image is also not "full" upgradeable, so you have to wait for upgrades from BTT.
So - I don't understand what sense makes this migration?

**Comment by ss1gohan13** [comment]
> Long time ago I upgraded my SV06+ with Klipper (thank's to bassam!) using a PTT Pi v1.2. This Board use the same BTT CB1 image as in this tutorial. This image is also not "full" upgradeable, so you have to wait for upgrades from BTT. So - I don't understand what sense makes this migration?

The point is to fork off of sovols terrible fork and use the mainline branch of klipper... How rude.

**Comment by cyaneo** [comment]
Thank you so much for explaining and made this possible! I will swich asap!
