### ISSUE TITLE
Latest klipper (28995a8bc) seems to break sv08

### ISSUE THREAD

**Issue by vvuk** [Rappetor/Sovol-SV08-Mainline#51]
Just moved to mainline klipper, and with very latest klipper (28995a8bc) I am getting a ton of "timer too close" errors trying to do anything. (Immediately triggered just trying to soak the bed; triggered partway through z offset calibration, etc.)

Looking at commits that landed today, they look suspicious -- some new gcode queueing functionality. I went back to `293858` which looked to be just before this and the issues went away.

**Comment by nick119** [comment]
Thanks for posting this, i too am having the same problem. Downgraded to 293858 as well, no issues.

**Comment by mon5termatt** [comment]
Suggest making a issue on Klipper as well.

**Comment by vvuk** [comment]
Can't; they don't do issues, I'd have to jump into their discord and I didn't really have time to engage :|

**Comment by vvuk** [comment]
This seems to be fixed in very latest sovol (they fixed the regression;  we just happened to get lucky and installed on the broken day!)
