### ISSUE TITLE
Pressure probe and z offest

### ISSUE THREAD

**Issue by Yousafkhan1976** [Rappetor/Sovol-SV08-Mainline#60]
Thank you for a perfect setup guide, I was able to get to the end without errors.

Now when I try to run z offset calibration, I get an error when the SAVE_CONFIG command executes.

"SAVE_CONFIG section 'probe' option 'z_offset' conflicts with included value"

**Comment by ss1gohan13** [comment]
Please link your config file. The stock sovol config should not result in this issue.

**Comment by Yousafkhan1976** [comment]
I have all the includes in my printer.cfg

[include mainsail.cfg]
[include sovol-macros.cfg]
[include timelapse.cfg]
[include options/lcd/*.cfg]
[include options/probe/stock.cfg]

**Comment by Yousafkhan1976** [comment]
I moved the [probe] section to printer.cfg and commented out the z-offset line. Now it works
