### ISSUE TITLE
update_klipper_mcus_sv08.sh not showing all necessary options

### ISSUE THREAD

**Issue by BoaTheCrafter** [Rappetor/Sovol-SV08-Mainline#61]
When running the modified update_klipper_mcus_sv08.sh, the menuconfig screen doesn`t show all options mentioned in step 8.8 and the corresponding note. 
Notable missing options are the bootloader offset and the communication interface as seen here:

![image](https://github.com/user-attachments/assets/a8b345e5-ee95-4864-b0da-0eed551b3d3c)

If you still run the script, it ends with the Error 

`mv: cannot stat '/home/biqu/klipper/out/klipper.bin': No such file or directory`

The Windows file formatting issue can be rolled out, since i used a Arch Linux based notebook for configuration.

The only changes, i've made to the script are as follows:

![image](https://github.com/user-attachments/assets/c241740d-6124-4ac2-b2bc-d10b34e77569)

The script is placed and executed in the ~/klipper directory

**Comment by Yousafkhan1976** [comment]
You need to change the Microcontroller Architecture to STM32

**Comment by BoaTheCrafter** [comment]
Oh my god. How did i overlook that lol

**Comment by BoaTheCrafter** [comment]
Currently not at home, but i'd guess so. Gonna close this, once i tried it

**Comment by BoaTheCrafter** [comment]
Yeah, fixed it. Guess i had just some brain lag
