### ISSUE TITLE
"SAVE_CONFIG section 'probe_eddy_current btt_eddy' option 'z_offset' conflicts with included value"

### ISSUE THREAD

**Issue by BoaTheCrafter** [Rappetor/Sovol-SV08-Mainline#97]
So i'm trying to get a good z offset and every time i run PROBE_CALIBRATE i get the above error whilst saving, and a "Error during homing probe: Eddy current sensor error" when i try to home without saving. Does the eddy.cfg provide a different macro for z-offset that i'm not seing? Or did i misconfigure something?

Added printer.cfg for reference
[config-20241121-145209.zip](https://github.com/user-attachments/files/17846872/config-20241121-145209.zip)

**Comment by Val-dose-things** [comment]
in the do not edit section in the printer.cfg remove:
#*# [probe]
#*# z_offset = 2.485

that fixed the error for me.
now it you are trying to save the new z- offset after a print that's a different issue. you need to change to a different set of configurations for that to work.
